# Cairo Taylor, First Program
name = input("What is your name, Traveler?:  ")
print("Hello", name)
print("My name is Biddle Diddle the Great")
place = input("Where do you wish to see?:  ")
print("I have been to", place,)
reason = input("What geographical feature makes you want to go?:  ")
print("The road there is difficult, and don't even get me started on how lame", reason, "is")
print("I would not reccomend going,", name)
print("The trip there will cost twice as much as you could ever own anyway")
print("*Biddle Diddle dabs and walks away*")