# Cairo Taylor Variables Practice
name = ("Cairo Taylor")
schoolname = ("Utah County Academy of Sciences (UCAS)")
randnumber1 = (4)
year = ("2025")
randnumber2 = ("276")
eye = ("blue-green color, but mostly blue")
brkfst = ("TOAST")
age = ("14")
color = ("aquamarine")
subject = ("biology")
print("Hello, my name is", name)
print("I go to", schoolname)
print("A random number I chose from 1 to 10 is", randnumber1)
print("This year is", year)
print("You get another random number, but this time it is from 100 to 1000, and I pick", randnumber2)
print("My eyes are a", eye)
print("Breakfast to me today was", brkfst)
print("I am", age, "years old")
print("My favorite color is", color)
print("My")